# Generated by Django 5.2.6 on 2025-09-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_almacen', models.CharField(choices=[('material', 'Material'), ('archivos', 'Archivos')], max_length=8)),
                ('ubicacion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nivel', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_estante', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
            },
        ),
        migrations.CreateModel(
            name='EstanteNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=8)),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.estante')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.nivel')),
            ],
            options={
                'verbose_name': 'Estante Nivel',
                'verbose_name_plural': 'Estantes Niveles',
                'constraints': [models.UniqueConstraint(fields=('estante', 'nivel'), name='unique_estante_nivel')],
            },
        ),
    ]
