# Generated by Django 5.2.6 on 2025-09-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('nro_item', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=45, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.departamento')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.unidad')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=9)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'constraints': [models.UniqueConstraint(fields=('nombre_personal', 'apellido_paterno', 'apellido_materno'), name='unique_nombre_apellidos')],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('nro_contrato', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=8)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cargo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.personal')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('departamento', 'unidad'), name='unique_departamento_unidad'),
        ),
    ]
